FROM --platform=$BUILDPLATFORM golang:buster AS build
ARG TARGETPLATFORM
ARG BUILDPLATFORM
RUN apt update && apt install build-essential gcc-arm-linux-gnueabi g++-arm-linux-gnueabihf -y
RUN echo "Building image on $BUILDPLATFORM for $TARGETPLATFORM"
WORKDIR /app
COPY . /app
RUN /app/gobuild_multi_arch.sh "$TARGETPLATFORM"

FROM debian:buster-slim
COPY --from=build /app/todo-api /todo-api
ENTRYPOINT [ "/todo-api" ]
