FROM --platform=$BUILDPLATFORM golang:alpine AS build
ARG TARGETPLATFORM
ARG BUILDPLATFORM
RUN apk update && apk add gcc libc-dev && rm -rf /var/cache/apk/*
RUN echo "Building image on $BUILDPLATFORM for $TARGETPLATFORM"
WORKDIR /app
COPY . /app
RUN chmod +x gobuild_multi_arch.sh
RUN /app/gobuild_multi_arch.sh "$TARGETPLATFORM"

FROM alpine
COPY --from=build /app/todo-api /todo-api
ENTRYPOINT [ "./todo-api" ]
